/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculadorasimples;





public class App {
    

    public static void main(String[] args) {
        calculadora calc = new calculadora ();
        System.out.println (calc.somar(5, 6));
        System.out.println (calc.subtrair(5, 6));
        System.out.println (calc.divisao(5, 6));
        System.out.println (calc.multiplicacao(5, 6));
      
        
    }
             
        
             
    }

